version: '3'

volumes:
  postgres_data: {}
  media_data: {}

services:
  postgres:
    image: postgres:15.2-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:7.0.9-alpine3.17
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /wait-for.sh postgres:5432 -- python manage.py runserver 0.0.0.0:8000
    # Fix mac m1 problem: https://stackoverflow.com/a/69636473
    platform: linux/amd64
    links:
      - postgres
      - redis
    volumes:
      - .:/app
      - media_data:/media
    ports:
      - "8000:8000"
    